version: '3.8'

services:
  app:
    image: golang:1.20
    container_name: go-sqlite-app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./database:/app/database
    environment:
      DATABASE_PATH: "/app/database/news.db"
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    command: >
      sh -c "
      go mod tidy && 
      go run main.go"
